typography_spectrum: 0.54633
color:
  brandColors:
    - '#ffffff'
    - '#ffe100'
    - '#000000'
    - '#0097db'
    - '#a3a3a3'
  brandStrength: 0.8125
  lightness: 0.954924498219043
  saturation: 0.8130009407177567
  rhythmicContrast: 0.2511236425489187
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13977
analytics:
  google: null
  facebook: null
  twitter: null
name: EMBARK
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Filling Gaps in Financial Environments
description: filling gaps in financial environments
purpose: []
