name: embark
favicon: null
layout_spectrum: 0.3174636475741863
typography_spectrum: 0.43668575515039265
title: Filling Gaps in Financial Environments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffe100'
    - '#000000'
    - '#0097db'
    - '#a3a3a3'
  brandStrength: 0.8125
  lightness: 0.954924498219043
  saturation: 0.8130009407177567
  rhythmicContrast: 0.2511236425489187
purpose: []
